CREATE TABLE `municipios` (
  `id`   	INT(11) UNSIGNED 	NOT NULL AUTO_INCREMENT,
  `nombre` 	VARCHAR(100) 		NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX id (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

INSERT INTO `municipios` (`nombre`) VALUES
  ('ALMIRANTE PADILLA'),
  ('BARALT'),
  ('CABIMAS'),
  ('CATATUMBO'),
  ('COLÓN'), 
  ('FRANCISCO JAVIER PULGAR'),
  ('JESÚS ENRIQUE LOSSADA'),
  ('JESIS MARÍA SEMPRÚN'),
  ('CAÑADA DE URDANETA'),
  ('LAGUNILLAS'),
  ('MACHIQUES DE PERIJÁ'),
  ('MARA'),
  ('MARACAIBO'),
  ('MIRANDA'),
  ('PÁEZ'),
  ('ROSARIO DE PERIJÁ'),
  ('SAN FRANCISCO'),
  ('SANTA RITA'),
  ('SIMÓN BOLÍVAR'),
  ('SUCRE'),
  ('VALMORE RODRÍGUEZ');
